version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:5341"
      - "8081:80"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  api:
    build:
      context: .
      dockerfile: ./src/Api/Dockerfile   # مسیر جدید
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # کلید JWT حداقل 32 بایت (اینجا نمونه hex طول 64 گذاشتیم - حتماً برای خودت عوضش کن)
      Auth__Jwt__Key: "2f1b9a0c5e0aa1d9fcb8e7a2e3f0b1c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f901"
      # اختیاری: Issuer/Audience
      # Auth__Jwt__Issuer: "EnterpriseBoilerplate"
      # Auth__Jwt__Audience: "EnterpriseBoilerplate.Clients"
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - mongo
      - seq
    ports:
      - "8080:8080"

  worker:
    build:
      context: .
      dockerfile: ./src/Worker/Dockerfile   # مسیر جدید
    environment:
      DOTNET_ENVIRONMENT: Development
    depends_on:
      - postgres
      - rabbitmq
      - mongo
      - seq

volumes:
  pgdata:
  mongodata: